## Forgot Password API

**Endpoint:** `/api/auth/forgot-password`

**Method:** `POST`

### Request Body
json
{
  "email": "string"
}
```
- **email**: The email address of the user requesting the password reset.

### Response

**Success Response:**
```json
{
  "message": "Reset password link sent to your email"
}
```
- **Status Code:** `200`

**Error Responses:**

- **User Not Found:**
  ```json
  {
    "message": "User not found"
  }
  ```
  - **Status Code:** `404`

- **Internal Server Error:**
  ```json
  {
    "message": "Error sending reset password link sent to your email: <error_message>"
  }
  ```
  - **Status Code:** `500`

### Description
Generates a reset token and sends a password reset link to the user's email. The reset token is valid for 1 hour.

## Reset Password API

**Endpoint:** `/api/auth/reset-password`

**Method:** `POST`

### Request Body
json
{
  "password": "string",
  "cPassword": "string",
  "email": "string" // found in the query params
}

- password: The new password the user wants to set.
- cPassword: Confirmation of the new password.
- email: The email address of the user resetting the password found in the query params.

### Response

**Success Response:**
```json
{
  "message": "Password has been reset successfully"
}
```
- **Status Code:** `200`

**Error Responses:**

- Password is Invalid:
  json
  {
    "message" : [
        "At least 8 characters",
        "Contain a number or symbol",
        "Password strength: Weak"
        ]
}

- Passwords Do Not Match:
  json
  {
    "message": "Passwords do not match"
  }
  - **Status Code:** `400`

- **User Not Found:**
  ```json
  {
    "message": "User not found"
  }
  ```
  - **Status Code:** `404`

- **Invalid or Expired Reset Token:**
  ```json
  {
    "message": "Reset token is invalid or has expired"
  }
  ```
  - **Status Code:** `400`

- **Invalid OTP:**
  ```json
  {
    "message": "Invalid OTP"
  }
  ```
  - **Status Code:** `400`

- **Internal Server Error:**
  ```json
  {
    "message": "Error resetting password: <error_message>"
  }
  ```
  - **Status Code:** `500`

### Description
Resets the user's password if the OTP and reset token are valid. The reset token and OTP must be provided within the token's validity period.

